### ISSUE TITLE
Figure out if we need SASS

### ISSUE THREAD

**Issue by KPeen** [Energinet-DataHub/MightyDucks#63]

**Comment by MrDach** [comment]
Installed a plugin in Figma to export variables - It exports them as CSS variables which means that SASS shouldn't be necessary for this part.
What we could use it for instead would be minifying the CSS and maybe mixins?

**Comment by Renetnielsen** [comment]
@MrDach Solved this issue in a simple and great way. So we can close this with the presumption that we are using SASS
