### ISSUE TITLE
Enabler feature: Segregate APIGateway into its own domain

### ISSUE THREAD

**Issue by KPeen** [Energinet-DataHub/MightyDucks#68]
We will get a more modular approach to the entire system, which will make it easier to develop and maintain features.
We will be able to deploy a single part of the system, without having to be afraid of breaking other parts.
We will be able to assign teams with ownership of domains (since they are now scoped to repositories), and therefor commit teams can be derived automatically, by using build in github features (teams).
It will be easier for a business owner, to grasp the system, since they can relate to the given domain they are in.

**Comment by Renetnielsen** [comment]
This will be a part of the shared ressources, so we can close this since its done for now

**Comment by KPeen** [comment]
@ftoft - vil du tage med @Renetnielsen om denne kan lukkes

**Comment by mogensjuul** [comment]
@Renetnielsen We close this based on that API can run for next PI
