### ISSUE TITLE
Define use case scenarios for feature toggling 

### ISSUE THREAD

**Issue by KPeen** [Energinet-DataHub/MightyDucks#86]
business - milestone toggling  - putting things on the shelf
archtitects - parameter and validation toggling - scope in/scope out toggling
test toggling - finished items, nonfinished items - dependency toggling
how do we test around toggling

**Comment by ASQ-EN** [comment]
It was suggested that feature toggling also could be used as part of release towards the market (beta releases for some external parties) should this be considered? @MartinFHansen
